version: '3.7'

networks:
  react-front-tier:
    name: react-starter-net

services:
  react-starter:
    hostname: localhost
    image: react-starter:1.0
    build:
      context: .
    container_name: react
    expose:
      - 80
    ports:
      - 8080:80
    restart: always
    networks:
      - react-front-tier
